### ISSUE TITLE
[Admin] [Rapoarte] Data aggregation doesn't work properly

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/hartareciclarii#13]
**Describe the bug**
Tried to create a report that contains data about 'Colectare separata deseuri' grouped by 'Judet'. The result was 0 for all the 'Judet' despite the fact that in 'Puncte harta' module I could see that there are added items for various counties.

**To Reproduce**
1. Go to 'Rapoarte'
2. Select from 'Tip serviciu' dropdown 'Colectare separata deseuri'
3. Select from 'Tip punct' dropdown 'Centru colectare'
4. Group information by 'Judet'
5. See error

**Expected behavior**
I should see the number of 'Centru colectare' from 'Colectare separata deseuri' by Judet

**Screenshots**
![Screenshot 2023-11-21 at 14 59 42](https://github.com/code4romania/hartareciclarii/assets/111346300/d50cf101-feff-4756-8aba-97df30d2091c)

**Desktop (please complete the following information):**
- OS: macOS
- Browser Chrome
- Version 119.0.6045.159 (Official Build) (arm64)

**Comment by iamBiB** [comment]
![image](https://github.com/code4romania/hartareciclarii/assets/12171894/68b890c4-6e3b-4459-b399-0e8ee3d0b2d2)

Apar, doar ca judetele in db le aveti salvate cu diacrictice iar pe punct de reciclare nu e adaugat cu diacritice.
probabil ca se va rezolva cand va face @madaeroblade modificarea de db cu id-uri in loc de string pe relatia judet, localitate
