### ISSUE TITLE
[Public user] Map is flickering

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#21]
**Describe the bug**
Following any move on the map (zoom in/out) or manual change of position, the screen is flickering

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Comment by madaeroblade** [comment]
Noi preluam informatiile bazate pe map-bounds si in momenul zoom/move, practic re-desenam harta, bazat pe pe ce informatii primim din API (puncte).
