### ISSUE TITLE
[Public user] Adăugare nou punct pe hartă/ Eroare confirmare

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#24]
**Describe the bug**

**To Reproduce**

1. Adăugare punct
2. Adaug adresa, dau plaseaza
4. merg mai departe
5. Administrat de bifez nu stiu
6. La final la confirmare, apas buton "Adauga punct" si primesc mesajul de eroare din printscreen

**Screenshots**
<img width="601" alt="Screenshot 2023-11-22 at 16 49 39" src="https://github.com/code4romania/hartareciclarii/assets/77338378/ee08860d-6777-453b-a129-c297861d3e82">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version

**Comment by lauramicle** [comment]
Cand introduc o adresa : Strada, Numar, Oras
Si cand apoi dau plaseaza pin
Se resecrie o adresa mai generica a strazii, fara numar
Iar pinul este plasat altundeva pe strada
Apare si un mesaj mic de eroare in casuta gri (vezi print screen)

<img width="608" alt="Adauga punct 1" src="https://github.com/code4romania/hartareciclarii/assets/77338378/d91db690-a3ad-4c66-af3e-e5ff792a8b5f">

<img width="610" alt="Adauga punct 2" src="https://github.com/code4romania/hartareciclarii/assets/77338378/fdf1aa3e-4c29-408d-b518-563397aa955e">

Inainte am mai patit si sa se blocheze harta, a trebuit sa redeschid in alta fereastra de chrome si sa reiau parocesul de adaugare punct
<img width="572" alt="Screenshot 2023-11-23 at 11 07 55" src="https://github.com/code4romania/hartareciclarii/assets/77338378/897a42d5-79c7-4631-84d0-380bc408f70a">

**Comment by lauramicle** [comment]
Nu ai da eroare dar In continuare, nu ia numarul strazii

<img width="617" alt="Screenshot 2023-11-23 at 11 30 06" src="https://github.com/code4romania/hartareciclarii/assets/77338378/e8a2b585-0e5d-4785-9d54-566e302d5bbd">

**Comment by mirunaioana-msc** [comment]
![Screenshot 2023-11-27 at 12 30 20](https://github.com/code4romania/hartareciclarii/assets/111346300/320f265e-04f6-4406-a7c3-2bd3a0f8dd52)

Mi se preia strada, numarul strazii etc insa la submit, nu raspunde server-ul (see printscreen above)

**Comment by madaeroblade** [comment]
Am testat acum cu informatiile pe care le-am vazut la tine in screenshot, si mi-a functionat.
