### ISSUE TITLE
[Public user]Search bar is not working

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#25]
**Describe the bug**
Search bar does not seem to be working on any search fields so far

**Screenshots**
Figma with dev notes
<img width="352" alt="Screenshot 2023-11-22 at 17 06 47" src="https://github.com/code4romania/hartareciclarii/assets/77338378/8268baa1-0abb-44db-ac52-c3516a23dcec">
Sunt in Iasi si vreau sa caut dupa baterii.Mai multe puncte sau toate colecteaza baterii acolo
<img width="994" alt="search mateiale" src="https://github.com/code4romania/hartareciclarii/assets/77338378/b08424f6-ccd8-4c04-a0b0-bfd8de2778b9">
Harta e plasata pe Timisoara si vreau sa caut in Iasi.  
<img width="447" alt="search oras" src="https://github.com/code4romania/hartareciclarii/assets/77338378/749cda2c-7501-4af8-9056-fe33a7ad21e7">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version

**Comment by overeha** [comment]
Describe the bug
Search bar does not return the results in a list format. I understand the Figma may have been misleading, however, the results need to be listed as well. 

[See figma  link](https://www.figma.com/file/FNH2WCgMs3sNMtKB8LJezI/Harta-Reciclarii-2.0?type=design&node-id=472-9191&mode=dev)

Screenshots
Figma with dev notes
Screenshot 2023-11-22 at 17 06 47

**Comment by madaeroblade** [comment]
Ce se intampla la click pe un element afisat? Center la harta pe acel punct + deschiderea elementului de detalii ?

**Comment by overeha** [comment]
Yes. That happens. It is correct. Center pe element afișat
