### ISSUE TITLE
[Public user][Dicționar] Butonul "Dictionar" nu ar trebui sa aiba un dropdown

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#27]
**Describe the bug**
Butonul Dictionar nu ar trebui sa aiba un dropdown.
In Figma erau doar versiuni de numire a butonului.

<img width="419" alt="Screenshot 2023-11-23 at 14 27 58" src="https://github.com/code4romania/hartareciclarii/assets/77338378/74bd18fa-9b10-4ef9-89e0-84dd04c0d951">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version

**Comment by madaeroblade** [comment]
care este denumirea corecta?

**Comment by lauramicle** [comment]
Dicționar
