### ISSUE TITLE
[Public User][Punct]Nu apare adresa

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#28]
**Describe the bug**
Nu apare adresa in pop-ul punctului

<img width="425" alt="Screenshot 2023-11-22 at 17 13 39" src="https://github.com/code4romania/hartareciclarii/assets/77338378/756611be-5033-4611-a091-984b2f748e5d">

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome
 - Version

**Comment by madaeroblade** [comment]
Nu are setata adresa in field types.
