### ISSUE TITLE
[Search] Search flow is not as described in design file

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/hartareciclarii#37]
**Describe the bug**
Currently, search flow is different than expected: search is performed as user types text in the searchbar, unstructured (searches in all point info).

**To Reproduce**
1. Go to (https://harta-reciclarii.staging.heroesof.tech/)
2. Click on search
3. Search "har"/"hart"

**Expected behavior**
Search behavior should follow the [behavior described in figma ](https://www.figma.com/file/FNH2WCgMs3sNMtKB8LJezI/Harta-Reciclarii-2.0?type=design&node-id=2298-40679&mode=design&t=qt0iq3Z2jArHLINm-4): 
1. User inputs text, eg. "hart" -> 2. Search dropdown appears with possible options ("hartie", address with "hart" in it, or search "hart" in other point details), along with the option to choose unstructured search -> 3. User selects an option to perform the search -> 4. search results are shown

the options in the list should be:
1. materials
2. point address
3. point name
4. other info
5. unstructured search: 
<img width="271" alt="image" src="https://github.com/code4romania/hartareciclarii/assets/95479576/0f81c76b-2c5f-4133-9810-02388ffe8427">

**Screenshots**
Current behavior:
https://github.com/code4romania/hartareciclarii/assets/95479576/c0402b44-b010-41c9-85fa-7c998fd86d26

**Additional**
Bugs reported in other issue

**Comment by overeha** [comment]
@anastk-code4 please update this with the correct behaviour as decided and link to Figma screens with Final UI. The agreed behavior is that the user will input the text it wants to search by, and the search will be done in 3 ways. (Example: "hartie" as materials type, as location - address - or unstructured search)  

If I search for "hartie" and i have no pin in my view port, the map should zoom out to catch the first available point with those characteristics. Emulate the "Expand your search" behaviour from Maps.

**Comment by gheorghelupu17** [comment]
here it's the old version
