### ISSUE TITLE
[Admin][Puncte hartă] Icons doar pe categorii de material, nu pe fiecare subcategorie material

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#38]
**Descrive the bug**
In coloana de materiale acum apare icon'ul corespunzator categoriei mamă pentru fiecare material colectat. Astfel, fiidnca avem mai multe materiale care fac parte din aceeasi categorie, icon-ul se repeta nejustificat.

**Expected behaviour*
Icon'ul trebuie sa apara doar pentru categoriile reprezentate.

**Screenshots**

![Screenshot 2023-12-11 at 14 45 27](https://github.com/code4romania/hartareciclarii/assets/77338378/f1d196cf-28b0-4e1e-9016-05577ebcf862)

![Screenshot 2023-12-11 at 14 45 35](https://github.com/code4romania/hartareciclarii/assets/77338378/34586fdd-0733-48ea-b8e4-664946d9e6bc)

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: Arc
 - Version 1.20.1

**Comment by iamBiB** [comment]
nu inteleg la ce te refero. iconitele apar doar pe cele pe care le adaugati

**Comment by anastk-code4** [comment]
se doreste sa apara iconita doar pentru categoria mare, de exemplu daca un punct primeste materialele:
categoria HARTIE SI CARTON (cu ambele subcategorii Hartie, Carton), vrem sa apara doar o iconita, pentru categoria HARTIE SI CARTON

acum apare iconita pentru subcategoria Hartie, iconita pentru subcategoria Carton si nu e ok dpdv usability
