### ISSUE TITLE
[Admin][Puncte harta] "Vezi pe harta" da eroare

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#40]
**Describe the bug**
[Admin][Puncte harta] "Vezi punct" da eroare

**To Reproduce**

1. Go to [Admin][Puncte harta]
2. Go to first point ID=1
3. Open the side menu (the three dots) And click "Vezi Harta"

**Expected behavior**
The public map should open in another window with the point selected 

**Screenshots**
![Screenshot 2023-12-11 at 16 04 25](https://github.com/code4romania/hartareciclarii/assets/77338378/23fa4001-64be-4774-b465-1bddb30bc839)

![Screenshot 2023-12-11 at 16 05 56](https://github.com/code4romania/hartareciclarii/assets/77338378/57d81138-a7d2-4c1d-bf78-40099e17da94)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 

.

**Comment by iamBiB** [comment]
nu  a fost definit in figma unde sa deschida si ce tip de harta sa deschida si ce sa faca. asa ca momentan l`am comentat pana veniti cu update

**Comment by anastk-code4** [comment]
_Expected behavior_
_The public map should open in another window with the point selected_

Adica la apasarea butonului "vezi pe harta", ar trebui sa se deschida portalul public, cu punctul respectiv selectat (view detalii punct), intr-un tab nou. Este practic un shortcut catre punctul respectiv in portal public. 
Exemplu:
Pentru punctul id 1
![image](https://github.com/code4romania/hartareciclarii/assets/95479576/9e3b5ba5-c5af-4187-b784-7bd9a99a50b9)
La click pe "vezi pe harta", se deschide portalul public cu view pe punctul cu id 1:
![image](https://github.com/code4romania/hartareciclarii/assets/95479576/e786c63c-a3f5-434d-970b-0d4fb6ace7c7)

Marchez cu low-priority si putem continua discutia pe slack.

**Comment by overeha** [comment]
@anastk-code4 please update here with link to final UI when done.

**Comment by anastk-code4** [comment]
this is a bug, it's not UI dependant. Expected behavior was already described.
