### ISSUE TITLE
[Admin][Puncte Harta] "Administrat de" se repeta in listing

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#41]
**Describe the bug**
[Admin][Puncte Harta] "Administrat de" se repeta in listing. 
Nu mai este nevoie, deoarece e in capul de tabel.

![Screenshot 2023-12-11 at 16 44 21](https://github.com/code4romania/hartareciclarii/assets/77338378/e76f6709-052c-4e93-8d1b-3a46bd520764)

**Comment by iamBiB** [comment]
pentru ca asa e in baza de date. va trebui modificat de mana
