### ISSUE TITLE
[Admin][Puncte hartă] Pentru unele puncte nu a preluat orasul si judetul

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#43]
**Describe the bug**
[Admin][Puncte hartă] Pentru unele puncte nu a preluat orasul si judetul in listingurile din tabel. Acestea apar in cadrul adresei.

Vezi punctele cu id 38 si 39 din printscreen

![Screenshot 2023-12-11 at 17 16 41](https://github.com/code4romania/hartareciclarii/assets/77338378/46b4ad12-9cd4-4193-808e-bea083cdc7ad)

**Comment by iamBiB** [comment]
nu a preluat orasul de unde? ca poate nu exista in db. adresa completa o ia din nominatim, n`are treaba cu ce e in db.
