### ISSUE TITLE
[Admin][Adaugare punct]Nu se pot selecta materiale, doar categorii de materiale

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#46]
**Describe the bug**
[Admin][Adaugare punct]
Cand adaug un punct din interfata de admin, nu pot selecta o subcategorie de materiale (ex. "Baterii"), cu toate ca la userul public pot face asta, insa in admin pot selecta doar categorii de materiale (ex. DEEE) selectand astfel si toate subcategoriile din categoria respectiva. 

**To Reproduce**
1. Go to Admin/ Adaugare punct
2. Alege tip punct s introdu adresa
3.Click Pasul urmator
4. La Material, in lista de dropdown sunt doar categoriile de materiale, lipsesc subcategoriile. (vezi printscreen) 

**Expected behavior**
Similar cu comportamentul din interfata publica: Utilizatorul trebuie sa poata selecta subcategorii de materiale care sunt colectate de un anumit punct, de exemplu, un punct de colectare poate primi doar subcategoria "Baterii" (din categoria DEEE).

Pentru lista completa de materiale, vezi Data Dictionary > Materiale (https://docs.google.com/spreadsheets/d/1FLFKIF4gsOU2H_Lo8wOWwh8A_Qn9LR9MeZizr95VfVM/edit#gid=1077405662)

**Screenshots**
![Screenshot 2023-12-11 at 19 00 09](https://github.com/code4romania/hartareciclarii/assets/77338378/6a3fb008-b18c-4977-86e5-fdfc9d88b133)

**Comment by iamBiB** [comment]
in figma nu am vazut nimic legat de categorii sau materiale. era un singur input cu toate. asa ca trebuie definit mai bine
