### ISSUE TITLE
[Admin][Adăugare punct]Nu se vede imaginea dupa ce a fost adaugata

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#47]
**Describe the bug**
Imaginile care tin de descrierea punctului (vizibile doar din interfata de admin), pot fi incarcate, insa nu mai sunt displayed niciunde dupa ce au fost incarcate.

Este necesar sa implementam o zona de view pentru aceste imagini, care sunt atasate fie de catre admin, fie de catre utilizatori publici:
- in momentul in care este adaugat un punct - atasament la Detalii punct [Figma](https://www.figma.com/file/FNH2WCgMs3sNMtKB8LJezI/Harta-Reciclarii-2.0?type=design&node-id=2518-65846&mode=design&t=cdlkzKGoReW7KHbS-4)
- in momentul in care se raporteaza o problema - atasament la Problema raportata [Figma](https://www.figma.com/file/FNH2WCgMs3sNMtKB8LJezI/Harta-Reciclarii-2.0?type=design&node-id=2624-72071&mode=design&t=cdlkzKGoReW7KHbS-4)

**To Reproduce**
https://github.com/code4romania/hartareciclarii/assets/77338378/6f2c97e2-3d82-4b0f-9c03-0c3df6274421

**Comment by iamBiB** [comment]
asta e update, nu exista in figma pe designul de admin sa se vada imaginea

**Comment by anastk-code4** [comment]
Asa este, nu a fost ilustrat cazul in Figma cu poze adaugate unui punct, exista mentiunea doar in data dictionary. 
<img width="1436" alt="image" src="https://github.com/code4romania/hartareciclarii/assets/95479576/874363b6-382d-419b-8b73-398e2bdb6e98">

Daca sunt incarcate imagini la adaugarea unui punct, acestea trebuie sa poata fi vizualizate de admin undeva, altfel nu ar fi fost puse in Figma deloc. 

Voi marca issue ca Low priority, si revin cand clarificam acest detaliu (unde ar trebui sa apara imaginile si daca pastram acest feature).

**Comment by anastk-code4** [comment]
updated initial issue text.
