### ISSUE TITLE
Câmpurile punctului difera in functie de tipul de serviciu al punctului

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#49]
Aceasta issue este o clarificare legată de câmpurile de informații care caracterizeaza un punct  (in functie de tipul de serviciu). See also Data dictionary > Detalii punct (https://docs.google.com/spreadsheets/d/1FLFKIF4gsOU2H_Lo8wOWwh8A_Qn9LR9MeZizr95VfVM/edit#gid=0)

Aceste variații au fost sugerate prin data dictionary iar ecranele dedicate sunt disponibile acum in [figma](https://www.figma.com/file/FNH2WCgMs3sNMtKB8LJezI/Harta-Reciclarii-2.0?type=design&node-id=2311-30708&mode=design&t=cdlkzKGoReW7KHbS-4
) pentru public user, flow-ul Adaugare Punct. Aceleasi diferente ar trebui sa se reflecte si la Adaugare Punct in Admin. 

Informațiile care caracterizează un punct variaza în funcție de tipul de serviciu astfel:

Colectare selectiva deșeuri:
Este bine cum este momentan: + Opțiunea _Oferă Voucher_ [Link Figma](https://www.figma.com/file/FNH2WCgMs3sNMtKB8LJezI/Harta-Reciclarii-2.0?type=design&node-id=149-9597&mode=design&t=HXv9BoiKwnkhVnTg-0)

Reparații:
Față de Colectare selectiva deșeuri, conține
-în plus numele business-ului PCT_BUSINESS și Servicii gratuite,
 -în minus câmpurile: Materiale colectate, Oferă bani, Oferă Transport, Oferă Voucher
[Link figma](https://www.figma.com/file/FNH2WCgMs3sNMtKB8LJezI/Harta-Reciclarii-2.0?type=design&node-id=1817-5175&mode=design&t=HXv9BoiKwnkhVnTg-0)
-toate câmpurile available de la început, fara content dinamic, see [dev notes](https://www.figma.com/file/FNH2WCgMs3sNMtKB8LJezI/Harta-Reciclarii-2.0?type=design&node-id=1845-5365&mode=design&t=csogzhUHIDE02NFf-0) lângă

Donații:
Față de Colectare selectiva deșeuri, conține
-în plus numele business-ului PCT_BUSINESS
-în minus câmpurile: Materiale colectate, Oferă bani, Oferă Voucher
[Link Figma](https://www.figma.com/file/FNH2WCgMs3sNMtKB8LJezI/Harta-Reciclarii-2.0?type=design&node-id=2388-47522&mode=design&t=cdlkzKGoReW7KHbS-4)
-toate câmpurile displayed de la început (see dev notes lângă)

Celelalte tipuri de servicii (Reutilizare, Reducere, Altele):
Față de Colectare selectiva deșeuri, ar trebui să conțină:
-în plus: numele business-ului PCT_BUSINESS
-în minus câmpurile: Materiale colectate, Oferă bani, Oferă transport, Oferă Voucher
[Link Figma](https://www.figma.com/file/FNH2WCgMs3sNMtKB8LJezI/Harta-Reciclarii-2.0?type=design&node-id=2392-49107&mode=design&t=cdlkzKGoReW7KHbS-4) 
-toate câmpurile displayed de la început (see dev notes lângă)

Aceste diferențe implică și niște variații 
- în felul cum arată punctele pe site-ul public, vezi exemple [link figma](https://www.figma.com/file/FNH2WCgMs3sNMtKB8LJezI/Harta-Reciclarii-2.0?type=design&node-id=2624-72067&mode=design&t=cdlkzKGoReW7KHbS-4)

- in capul de tabel la Puncte Harta in Admin
- in filtre
- in structura de import în functie de tipul serviciului.

**Comment by overeha** [comment]
@anastk-code4 please confirm that this issue is correctly listed and explained. Link to data dictionary or figma screen/dev notes where the expected structure of information is correctly explained. Assign issue to @gheorghelupu17 when done.
