### ISSUE TITLE
[Admin] [Puncte harta] Table responsiveness issue

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/hartareciclarii#5]
**The bug**
The responsiveness of the items in the table is problematic. Some of them overlap on small screens.

**Screenshots**

<img width="1074" alt="Screenshot 2023-11-21 at 13 23 20" src="https://github.com/code4romania/hartareciclarii/assets/111346300/148cdb26-daf3-4465-8d1e-4b7ca07249fe">

**Expected behavior**

Only 2-3 categories should be displayed and the rest should be +2

![Screenshot 2023-11-21 at 13 54 59](https://github.com/code4romania/hartareciclarii/assets/111346300/fd8878bc-e3ae-4c99-987e-c40c7e993c31)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 119.0.6045.159 (Official Build) (arm64)

**Comment by iamBiB** [comment]
nu merge facut cu +2, le`am pus unele sub altele

**Comment by gheorghelupu17** [comment]
@iamBiB  a rezolvat @madaeroblade
