### ISSUE TITLE
[Probleme raportate] [Vizualizare] "Vezi punct" should open in a new tab 

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#59]
In Admin, la vizualizare unei probleme raporatate, vezi punct ar trebui sa deschida modul de editare a punctului intr-un nou tab.

To reproduce:

1. Go to admin
2. Go to Probleme raportate
3. Go to one of the  listings and click Detalii
4.You are now in the problem visualisation screen and you should click "Vezi punct"
5. The point details now open in the same tab. 

Expected behavior:
The point details should open in a different tab (so I can see both the point and the problem by switching tabs and not by pressing the back button in the browser)

![Screenshot 2023-12-15 at 17 32 53](https://github.com/code4romania/hartareciclarii/assets/77338378/67be8a09-4858-4d2f-9208-7e70ece3db52)

**Comment by iamBiB** [comment]
updated in #58
