### ISSUE TITLE
[Admin] [Puncte harta] [Adauga punct nou] Can't change the address of the point

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/hartareciclarii#6]
**The bug**
The input field where the address of the point is written is disabled and I can't change it

**To Reproduce**
1. Go to 'Puncte harta'
2. Click on 'Adauga punct nou'

**Expected behavior**
The user should be able to add an address to the input field.

**Screenshots**

![Screenshot 2023-11-21 at 13 28 11](https://github.com/code4romania/hartareciclarii/assets/111346300/dc93c546-9329-4753-ad04-accf343c6fce)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 119.0.6045.159 (Official Build) (arm64)

**Comment by iamBiB** [comment]
am discutat asta. nu se poate face fara reverse. iar noi nu avem acces la un reverse gratuit
