### ISSUE TITLE
'Jump to location' feature is missing

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/hartareciclarii#61]
**Describe the bug**
User needs a shortcut to jump to a location on the map, in order to avoid dragging the map around to find a specific city if the location services are not available for whatever reason.

**To Reproduce**
1. Go to ['...'](https://harta-reciclarii.staging.heroesof.tech/)

**Expected behavior**
[As described in Figma: ](https://www.figma.com/file/FNH2WCgMs3sNMtKB8LJezI/Harta-Reciclarii-2.0?type=design&node-id=457-7457&mode=design&t=9eAOKqDUNyudvmPK-4)
1. User clicks on "Sari la locatie" button
2. User searches for a location (UAT - a city or a county)
3. User clicks on the desired location
4. Map is repositioned to that location 

**Screenshots**
-

**Comment by overeha** [comment]
@anastk-code4 please link to figma screens once UI is done for this flow.
