### ISSUE TITLE
[Adăugare punct] Pentru unele adrese pinul nu este plasat corect

### ISSUE THREAD

**Issue by lauramicle** [code4romania/hartareciclarii#66]
**Describe the bug**
La adaugarea unui punct pe hartă, pentru unele adrese pinul nu este plasat corect.

**To Reproduce**
1. Go public map
2. Click on Adauga punct
3. Introduce address "Aleea F.C. Ripensia 15, Timisoara" and click Plasează pin

**Expected behavior**
The pin should be place at the introduced address.
Instead it is placed almost 600 away, see screen recording

**Screenrecording**

https://github.com/code4romania/hartareciclarii/assets/77338378/56f4d5cd-ac1a-4d16-b289-f4605af670d5

**Comment by madaeroblade** [comment]
We display the point according to the nominatim coordinates.
