### ISSUE TITLE
[Admin] [Puncte harta] [Adauga punct nou] HTTP 500 Internal Server Error when submitting the form

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/hartareciclarii#7]
**Describe the bug**
When clicking on submit after completing the data required to add a new point on the map I got HTTP 500 Internal Server Error

**To Reproduce**
1. Go to 'Puncte harta'
2. Complete the form 
3. Click on 'Submit'

**Expected behavior**
The point should be added in the table with the status "Validat"

**Screenshots**

![Screenshot 2023-11-21 at 13 32 12](https://github.com/code4romania/hartareciclarii/assets/111346300/693a075b-60f2-4c11-a78b-3a14d7c860d2)

**Desktop (please complete the following information):**
- OS: macOS
- Browser Chrome
- Version 119.0.6045.159 (Official Build) (arm64)

**Comment by iamBiB** [comment]
ce date ai adaugat? ca eu n`am putut sa replic

**Comment by gheorghelupu17** [comment]
@iamBiB  vezi te rog cu data de baze actualizata.
